# Nome dell'applicazione
spring.application.name=aulab_chronicle

# Configurazione del Datasource MySQL (Moderna e Sicura)
spring.datasource.url=jdbc:mysql://localhost:3306/aulabChronicle?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=rootroot
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurazione Hibernate JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CONFIGURAZIONE SUPABASE STORAGE
supabase.url=https://ugunmluumlvhuiplvmqa.supabase.co
supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVndW5tbHV1bWx2aHVpcGx2bXFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkwMjEwOTAsImV4cCI6MjEwNDU5NzA5MH0.jREcEtOagmGiU47HWSauom2_fQ-BnfTMSb05HVHvIGQ
supabase.bucket=/storage/v1/object/aulab_chronicle/
supabase.image=/storage/v1/object/public/aulab_chronicle/

# CONFIGURAZIONE MAILTRAP
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=b072f525ac21db
spring.mail.password=aa9033e0ea3d1b
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true