# Nome dell'applicazione
spring.application.name=aulab_chronicle

# Configurazione del Datasource MySQL (Moderna e Sicura)
spring.datasource.url=jdbc:mysql://localhost:3306/aulabChronicle?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:rootroot}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurazione Hibernate JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CONFIGURAZIONE SUPABASE STORAGE
supabase.url=https://ugunmluumlvhuiplvmqa.supabase.co
supabase.key=${SUPABASE_KEY:}
supabase.bucket=/storage/v1/object/aulab_chronicle/
supabase.image=/storage/v1/object/public/aulab_chronicle/

# CONFIGURAZIONE MAILTRAP
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
